from_latest_tag = false
ignore_merge_commits = true
disable_changelog = false
tag_prefix="v"
disable_bump_commit = false
generate_mono_repository_global_tag = true
branch_whitelist = ["main"]
skip_ci = "[skip ci]"
skip_untracked = false
pre_bump_hooks = [
    "yq -i '.version=\"{{version}}\"' charts/powerdns-pdns/Chart.yaml",
    "helm-docs -s file",
]
post_bump_hooks = [
    "git push",
    "git push origin v{{version}}"
]
pre_package_bump_hooks = []
post_package_bump_hooks = []

[git_hooks]

[commit_types]
improvement = { changelog_title = "Improvements", bump_patch = true }
chore = { changelog_title = "Chore", omit_from_changelog = true }
ci = { changelog_title = "", omit_from_changelog = true }
perf = { changelog_title = "", omit_from_changelog = true }

[changelog]
path = "CHANGELOG.md"
remote = "github.com"
repository = "witcom-docker-powerdns"
owner = "witcom-gmbh"
authors = [
    { signature = "Carsten Buchberger", username = "iceman91176" }
]

[bump_profiles]

[packages]
