{{- if .Values.pdns.web.api.apiKey }}
apiVersion: v1
type: Opaque
data:
  {{ .Values.pdns.web.api.secretKey | default "apikey" }}: "{{ .Values.pdns.web.api.apiKey | b64enc }}"
kind: Secret
metadata:
  name: {{ printf "%s-api" ( include "powerdns-pdns.fullname" .) }}
  labels:
    {{- include "powerdns-pdns.labels" . | nindent 4 }}
{{- end }}
