{{- if .Values.service.udp.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ printf "%s-udp" ( include "powerdns-pdns.fullname" .) }}
  labels:
    {{- include "powerdns-pdns.labels" . | nindent 4 }}
  {{- with .Values.service.udp.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}    
spec:
  type: {{ .Values.service.udp.type | default "ClusterIP" }}
  {{ if eq .Values.service.udp.type "LoadBalancer" -}}
  externalTrafficPolicy: {{ .Values.service.udp.externalTrafficPolicy | default "Cluster" }}
  {{ if .Values.service.udp.loadBalancerIP -}}loadBalancerIP: {{ .Values.service.udp.loadBalancerIP }}{{- end }}
  {{- end -}}
  {{ if and (eq .Values.service.udp.type "ClusterIP") (.Values.service.udp.clusterIP) -}}clusterIP: {{ .Values.service.udp.clusterIP }}{{- end }}
  ports:
    - port: 53
      targetPort: 53
      protocol: UDP
      name: dns-udp
  selector:
    {{- include "powerdns-pdns.selectorLabels" . | nindent 4 }}
{{- end }}