apiVersion: v1
kind: Service
metadata:
  name: {{ include "powerdns-pdns.fullname" . }}
  labels:
    {{- include "powerdns-pdns.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.web.type }}
  ports:
    - port: {{ .Values.service.web.port }}
      targetPort: http
      protocol: TCP
      name: http
#    - port: 53
#      targetPort: dns-tcp
#      protocol: TCP
#      name: dns-tcp
#    - port: 53
#      targetPort: dns-udp
#      protocol: UDP
#      name: dns-udp
  selector:
    {{- include "powerdns-pdns.selectorLabels" . | nindent 4 }}
