{{- if .Values.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    {{- include "powerdns-pdns.labels" . | nindent 4 }}
    {{- with .Values.serviceMonitor.labels }}
        {{- toYaml . | nindent 4 }}
    {{- end }}
  name: {{ include "powerdns-pdns.fullname" . }}
spec:
  endpoints:
  - honorLabels: true
    interval: {{ .Values.serviceMonitor.interval }}
    port: http
    path: /metrics
    relabelings:
    - action: replace
      regex: ([^:]+)(:[0-9]+)?
      replacement: ${1}
      sourceLabels:
      - __address__
      targetLabel: instance
    - action: replace
      sourceLabels:
      - __meta_kubernetes_endpoints_label_app_kubernetes_io_instance
      targetLabel: job
  selector:
    matchLabels:
      {{- include "powerdns-pdns.selectorLabels" . | nindent 6 }}
{{- end }}