{{- if .Values.service.tcp.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ printf "%s-tcp" ( include "powerdns-pdns.fullname" .) }}
  labels:
    {{- include "powerdns-pdns.labels" . | nindent 4 }}
  {{- with .Values.service.tcp.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}    
spec:
  type: {{ .Values.service.tcp.type | default "ClusterIP" }}
  {{ if eq .Values.service.tcp.type "LoadBalancer" -}}
  externalTrafficPolicy: {{ .Values.service.tcp.externalTrafficPolicy | default "Cluster" }}
  {{ if .Values.service.tcp.loadBalancerIP -}}loadBalancerIP: {{ .Values.service.tcp.loadBalancerIP }}{{- end }}
  {{- end -}}
  {{ if and (eq .Values.service.tcp.type "ClusterIP") (.Values.service.tcp.clusterIP) -}}clusterIP: {{ .Values.service.tcp.clusterIP }}{{- end }}
  ports:
    - port: 53
      targetPort: 53
      protocol: TCP
      name: dns-tcp
  selector:
    {{- include "powerdns-pdns.selectorLabels" . | nindent 4 }}
{{- end }}