{{ include "database.isConfigured" . }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "powerdns-pdns.fullname" . }}
  labels:
    {{- include "powerdns-pdns.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "powerdns-pdns.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        checksum/configmap-env-vars: {{ include (print $.Template.BasePath "/configmap-env-vars.yaml") . | sha256sum }}
      {{- with .Values.podAnnotations }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "powerdns-pdns.selectorLabels" . | nindent 8 }}
      {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "powerdns-pdns.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      {{ if .Values.pdns.database.init.enabled -}}
      initContainers:
        - env:
            - name: FLYWAY_BASELINE_ON_MIGRATE
              value: {{ .Values.pdns.database.init.baseline | quote }}
            - name: FLYWAY_DBHOST
              value: {{ .Values.pdns.database.host }}
            - name: FLYWAY_DBNAME
              value: {{ .Values.pdns.database.db }}
            - name: FLYWAY_USER
              value: {{ .Values.pdns.database.user }}
            - name: FLYWAY_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: {{ .Values.pdns.database.secretKey }}
                  name: {{ .Values.pdns.database.existingSecret | default (printf "%s-db" (include "powerdns-pdns.fullname" .)) }}
          image: "{{ .Values.initImage.repository }}:{{ .Values.initImage.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.initImage.pullPolicy }}
          name: init-powerdns-db
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
          - name: PDNS_gmysql_password
            valueFrom:
              secretKeyRef:
                key: {{ .Values.pdns.database.secretKey }}
                name: {{ .Values.pdns.database.existingSecret | default (printf "%s-db" (include "powerdns-pdns.fullname" .)) }} 
          {{ if .Values.pdns.web.api.enabled -}}  
          - name: PDNS_api_key
            valueFrom:
              secretKeyRef:
                key: {{ .Values.pdns.web.api.secretKey }}
                name: {{ .Values.pdns.web.api.existingSecret | default (printf "%s-api" (include "powerdns-pdns.fullname" .)) }} 
          {{- end }}              
          envFrom:
            - configMapRef:
                name: {{ printf "%s" (include "powerdns-pdns.fullname" .) }}
          ports:
            {{ if .Values.pdns.web.enabled -}}
            - name: http
              containerPort: {{ .Values.service.web.port }}
              protocol: TCP
            {{- end }}  
            - name: dns-udp
              containerPort: 53
              protocol: UDP
            - name: dns-tcp
              containerPort: 53
              protocol: TCP
          livenessProbe:
            exec:
              command:
              - pdns_control
              - rping  
          startupProbe:
            exec:
              command:
              - pdns_control
              - rping
            failureThreshold: 12
            periodSeconds: 10
          readinessProbe:
            exec:
              command:
              - pdns_control
              - rping
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
