{{- if eq (include "dbbackup.createSecret" .) "true" }}
apiVersion: v1
type: Opaque
data:
  {{ .Values.pdns.database.backup.s3.accessKeyIdSecretKey }}: "{{ .Values.pdns.database.backup.s3.accessKeyId | b64enc }}"
  {{ .Values.pdns.database.backup.s3.secretAccessKeySecretKey }}: "{{ .Values.pdns.database.backup.s3.secretAccessKey | b64enc }}"
kind: Secret
metadata:
  name: {{ include "dbbackup.secretName" . }}
  labels:
    {{- include "powerdns-pdns.labels" . | nindent 4 }}
{{- end }}