{{- if not .Values.pdns.web.api.existingSecret }}
apiVersion: v1
type: Opaque
data:
  {{ .Values.pdns.web.api.secretKey | default "apikey" }}: {{ .Values.pdns.web.api.apiKey | default (randAlphaNum 32) | b64enc | quote }} 
kind: Secret
metadata:
  name: {{ printf "%s-api" ( include "powerdns-pdns.fullname" .) }}
  labels:
    {{- include "powerdns-pdns.labels" . | nindent 4 }}
{{- end }}
