{{- if .Values.pdns.database.password }}
apiVersion: v1
type: Opaque
data:
  {{ .Values.pdns.database.secretKey | default "password" }}: "{{ .Values.pdns.database.password | b64enc }}"
kind: Secret
metadata:
  name: {{ printf "%s-db" ( include "powerdns-pdns.fullname" .) }}
  labels:
    {{- include "powerdns-pdns.labels" . | nindent 4 }}
{{- end }}
