{{- if .Values.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    {{- include "powerdns-pdns.labels" . | nindent 4 }}
    {{- with .Values.serviceMonitor.labels }}
        {{- toYaml . | nindent 4 }}
    {{- end }}
  name: {{ include "powerdns-pdns.fullname" . }}
spec:
  jobLabel: {{ .Values.serviceMonitor.jobLabel | quote }}
  endpoints:
  - port: http
    {{- if .Values.serviceMonitor.scrapeTimeout }}
    scrapeTimeout: {{ .Values.serviceMonitor.scrapeTimeout }}
    {{- end }}
    {{- if .Values.serviceMonitor.honorLabels }}
    honorLabels: {{ .Values.serviceMonitor.honorLabels }}
    {{- end }}
    {{- if .Values.serviceMonitor.metricRelabelings }}
    metricRelabelings: {{- include "common.tplvalues.render" ( dict "value" .Values.serviceMonitor.metricRelabelings "context" $) | nindent 8 }}
    {{- end }}
    {{- if .Values.serviceMonitor.relabelings }}
    relabelings: {{- include "common.tplvalues.render" ( dict "value" .Values.serviceMonitor.relabelings "context" $) | nindent 8 }}
    {{- end }}
    {{- if .Values.serviceMonitor.interval }}
    interval: {{ .Values.serviceMonitor.interval }}
    {{- end }}  
    path: /metrics
  selector:
    matchLabels:
      {{- include "powerdns-pdns.selectorLabels" . | nindent 6 }}
{{- end }}